---
title: "eds212-day2-tasks"
author: "Melannie Moreno Rolon"
format: html
editor: visual
---

# Section 3: Derivatives in R

```{r}
#attaching libraries
library(tidyverse)
library(palmerpenguins)
```

## Finding derivatives using R

### *f(x) = x\^2 at x= 3*

```{r}
#expression
fx <- expression(x^2)

#derivative with respect to x
df <- D(expr = fx, name = "x")
df

#evaluate slope at x = 3
x <- 3
eval(df)
```

### *P(a) = 2(3a +2)\^4 - 5 at a = 1.2*

```{r}
#create exoression
dp <- expression(2 * (3 * a + 2)^4 - 5)

#derivative with respect to a 
dp_da <- D(expr = dp, name = "a")
dp_da

#evaluate slope at a = 1.2
a <- 1.2
eval(dp_da)
```

# Section 4: Make another penguin plot

```{r}
#adding libraries
library(tidyverse)
library(ggplot2)
library(palmerpenguins)
```

```{r}

# create plot ----
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species)) +
  scale_color_manual(values = c("orange","purple","cyan4")) +
  labs(x = "Bill Length (mm)",
       y = "Bill Depth (mm)",
       title = "Palmer penguin bill size measurements",
       subtitle = "Palmer Archipelago, Antarctica (2007 - 2009)",
       caption = "Collected by Dr. Kristen Gorman and colleagues at Palmer Station LTER") +
  facet_wrap(~island) +
  theme_minimal()
```

```{r}
#jitter plot of flipper length by species
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) + 
         geom_jitter(aes(color = species)) + 
  scale_color_manual(values = c("orange", "purple", "cyan4")) + 
  labs(x = "Species",
       y = "Flipper Length (mm)",
       title = "Flipper length variation by species ",
       subtitle = "Palmer Archipelago, Antarctica (2007 - 2009)",
       caption = "Collected by Dr. Kristen Gorman and colleagues at Palmer Station LTER") +
  facet_wrap(~island) + 
    theme_minimal()
```
